# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PediatricSensor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PediatricSensor
pod 'SwiftyBluetooth', '1.0.0'
pod 'LGBluetooth', '~> 1.1.5'
pod 'Alamofire', '~> 4.5.1'
pod 'ScrollableGraphView', '~> 4.0.4'
pod 'ANLoader', :git => 'https://github.com/ANSCoder/ANLoader.git'
pod 'RATreeView', '~> 2.1.2'

  target 'PediatricSensorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PediatricSensorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
